# Generated by Django 3.0.7 on 2020-06-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bankaccount',
            fields=[
                ('bankaccount_id', models.AutoField(db_column='Bankaccount_id', primary_key=True, serialize=False)),
                ('account', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bankaccount',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Brigade',
            fields=[
                ('brigade_id', models.AutoField(db_column='Brigade_id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'brigade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Brigadeleader',
            fields=[
                ('brigadeleader_id', models.AutoField(db_column='Brigadeleader_id', primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('patronym', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'brigadeleader',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Brigadeworker',
            fields=[
                ('brigadeworker_id', models.AutoField(db_column='Brigadeworker_id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'brigadeworker',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(db_column='Customer_id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(db_column='Department_id', primary_key=True, serialize=False)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ordercustomer',
            fields=[
                ('ordercustomer_id', models.AutoField(db_column='Ordercustomer_id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ordercustomer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orderproduct',
            fields=[
                ('orderproduct_id', models.AutoField(db_column='Orderproduct_id', primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orderproduct',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Premium',
            fields=[
                ('premium_id', models.AutoField(db_column='Premium_id', primary_key=True, serialize=False)),
                ('premium', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'premium',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Premiumbudget',
            fields=[
                ('premiumbudget_id', models.AutoField(db_column='Premiumbudget_id', primary_key=True, serialize=False)),
                ('month', models.CharField(blank=True, max_length=255, null=True)),
                ('budget', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'premiumbudget',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(db_column='Product_id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productionjournal',
            fields=[
                ('productionjournal_id', models.AutoField(db_column='Productionjournal_id', primary_key=True, serialize=False)),
                ('quantity', models.SmallIntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'productionjournal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productionplan',
            fields=[
                ('productionplan_id', models.AutoField(db_column='Productionplan_id', primary_key=True, serialize=False)),
                ('quantity', models.SmallIntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'productionplan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('rack_id', models.AutoField(db_column='Rack_id', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rack',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rackfreesize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freesize', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rackfreesize',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rackoccupiedsize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupiedsize', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rackoccupiedsize',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Racksize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'racksize',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vacationcalendar',
            fields=[
                ('vacationcalendar_id', models.AutoField(db_column='Vacationcalendar_id', primary_key=True, serialize=False)),
                ('firstdate', models.DateField(blank=True, null=True)),
                ('lastdate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vacationcalendar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wage',
            fields=[
                ('wage_id', models.AutoField(db_column='Wage_id', primary_key=True, serialize=False)),
                ('wage', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('worker_id', models.AutoField(db_column='Worker_id', primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, max_length=255, null=True)),
                ('lastname', models.CharField(blank=True, max_length=255, null=True)),
                ('patronymic', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'worker',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Workerexperience',
            fields=[
                ('workerexperience_id', models.AutoField(db_column='Workerexperience_id', primary_key=True, serialize=False)),
                ('firstdate', models.DateField(blank=True, null=True)),
                ('expdate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'workerexperience',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Workerfullinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phonenumber', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'workerfullinfo',
                'managed': False,
            },
        ),
    ]
